class ApiConstants {
  static const int sendTimeoutSeconds = 60;
  static const int receiveTimeoutSeconds = 60;
  static const String bearer = 'Bearer';
  static const String applicationJson = 'application/json';
  static const String baseUrl = 'https://discount-platform.onrender.com/api/';
  static const String register = '${baseUrl}auth/register';
  static const String registerByGoogle = '${baseUrl}auth/register-by-google';
  static const String logout = '${baseUrl}auth/logout';
  static const String resendOtp = '${baseUrl}auth/resend-otp';
  static const String resetPassword = '${baseUrl}users/me/password';
  static const String verifyOtp = '${baseUrl}auth/verify-otp';
  static const String updateProfile = '${baseUrl}users/me';
  static const String updateProfileAvatar = '${baseUrl}users/me/avatar';
  static const String login = '${baseUrl}auth/login';
  static const String loginByGoogle = '${baseUrl}auth/login';
  static const String forgotPassword = '${baseUrl}auth/forgot-password';
  static const String profile = '${baseUrl}auth/me';
  static const String editProfile = '${baseUrl}users/';
  static const String sectors = '${baseUrl}vendors/';
  static const String home = '${baseUrl}home';
  static const String getAllFavoriteOffers = '${baseUrl}favorites/offers/my';
  static const String addOrDeleteFavoriteOffer = '${baseUrl}favorites/offers/';
  static const String getAllOffers = '${baseUrl}offers/active';
  static const String offers = '${baseUrl}offers';
  static const String getOfferDetails = '${baseUrl}offers/';
  static const String offerClaims = '${baseUrl}offer-claims';
  static const String getVendorDetails = '${baseUrl}vendors/public/';
  static const String getAllVendor = '${baseUrl}vendors/public';
}

class ApiKeys {
  static const String contentType = 'Content-Type';
  static const String xClientPlatform = 'x-client-platform';
  static const String authorization = 'Authorization';
  static const String message = 'message';
  static const String mobile = 'mobile';
  static const String page = 'page';
  static const String take = 'take';
  static const String query = 'q';
  // Login / generic response keys
  static const String success = 'success';
  static const String statusCode = 'statusCode';
  static const String timestamp = 'timestamp';
  static const String path = 'path';
  static const String data = 'data';
  static const String text = 'text';

  // Auth / user keys
  static const String user = 'user';
  static const String token = 'token';
  static const String id = 'id';
  static const String firstName = 'first_name';
  static const String lastName = 'last_name';
  static const String phoneNumber = 'phone_number';
  static const String email = 'email';
  static const String role = 'role';
  static const String governorate = 'governorate';
  static const String wilaya = 'wilaya';
  static const String status = 'status';
  static const String fcmToken = 'fcm_token';
  static const String avatarUrl = 'avatar_url';
  static const String avatar = 'avatar';
  static const String avatarPublicId = 'avatar_public_id';
  static const String createdAt = 'created_at';
  static const String updatedAt = 'updated_at';
  static const String password = 'password';
  static const String currentPassword = 'current_password';
  static const String newPassword = 'new_password';
  static const String passwordConfirm = 'password_confirm';
  static const String requiresVerification = 'requires_verification';
  static const String otp = 'otp';
  static const String otpType = 'otp_type';
  static const String resetToken = 'reset_token';
  static const String registrationType  = 'REGISTRATION';
  static const String passwordResetToken  = 'password_reset_token';
  static const String passwordResetExpires  = 'password_reset_expires';
  static const String isVerified  = 'is_verified';
  static const String otpExpires  = 'otp_expires';
  static const String otpAttempts  = 'otp_attempts';
  static const String lastOtpSentAt  = 'last_otp_sent_at';
  static const String otpHash  = 'otp_hash';

  // Sector keys
  static const String name = 'name';
  static const String iconUrl = 'icon_url';
  static const String isActive = 'is_active';
  static const String isComingSoon = 'is_coming_soon';
  static const String meta = 'meta';
  static const String count = 'count';
  static const String vendors = 'vendors';

  // Home / offers keys
  static const String title = 'title';
  static const String imageUrl = 'image_url';
  static const String discountPercentage = 'discount_percentage';
  static const String redemptionType = 'redemption_type';
  static const String discountCode = 'discount_code';
  static const String claimCode = 'claim_code';
  static const String barcodeImageUrl = 'barcode_image_url';
  static const String whatsappNumber = 'whatsapp_number';
  static const String whatsappMessageTemplate = 'whatsapp_message_template';
  static const String vendorPrimaryPhoneNumber = 'vendor_primary_phone_number';
  static const String redeemedAt = 'redeemed_at';
  static const String expiresAt = 'expires_at';
  static const String validUntil = 'valid_until';
  static const String businessName = 'business_name';
  static const String sectorName = 'sector_name';
  static const String city = 'city';
  static const String totalClaims = 'total_claims';
  static const String distanceKm = 'distance_km';

  // Home cursors keys
  static const String offersNextCursor = 'offers_next_cursor';
  static const String hotelsNextCursor = 'hotels_next_cursor';
  static const String recommendedNextCursor = 'recommended_next_cursor';
  static const String storesNextCursor = 'stores_next_cursor';
  static const String offers = 'offers';
  static const String sectors = 'sectors';
  static const String bestHotels = 'best_hotels';
  static const String recommended = 'recommended';
  static const String stores = 'stores';
  static const String store = 'store';
  static const String isFavorited = 'is_favorited';
  static const String cursors = 'cursors';
  static const String logoUrl = 'logo_url';
  
  // Favorite offers & vendor/offer details keys
  static const String userId = 'user_id';
  static const String offerId = 'offer_id';
  static const String offer = 'offer';
  static const String parentOfferId = 'parent_offer_id';
  static const String favorite = 'favorite';
  static const String sector = 'sector';
  static const String vendorId = 'vendor_id';
  static const String vendor = 'vendor';
  static const String description = 'description';
  static const String licenseNumber = 'license_number';
  static const String codeMode = 'code_mode';
  static const String codePrefix = 'code_prefix';
  static const String minPurchaseAmount = 'min_purchase_amount';
  static const String validFrom = 'valid_from';
  static const String totalViews = 'total_views';
  static const String maxTotalClaims = 'max_total_claims';
  static const String maxClaimsPerUser = 'max_claims_per_user';
  static const String termsAndConditions = 'terms_and_conditions';
  static const String appliesToAllBranches = 'applies_to_all_branches';
  static const String offerBranches = 'offer_branches';
  static const String sectorId = 'sector_id';
  static const String workingHours = 'working_hours';
  static const String maxOffersAllowed = 'max_offers_allowed';
  static const String monthlyClaimsLimit = 'monthly_claims_limit';
  static const String planId = 'plan_id';
  static const String adminNotes = 'admin_notes';
  static const String websiteUrl = 'website_url';
  static const String instagramUrl = 'instagram_url';
  static const String facebookUrl = 'facebook_url';
  static const String tiktokUrl = 'tiktok_url';
  static const String snapchatUrl = 'snapchat_url';

  // Offers active list extra keys
  static const String branches = 'branches';
  static const String address = 'address';
  static const String latitude = 'latitude';
  static const String longitude = 'longitude';
  static const String isMain = 'is_main';
  static const String effectiveStatus = 'effective_status';
  static const String lifecycleActions = 'lifecycle_actions';
  static const String isClaimable = 'is_claimable';
  static const String activeOffersCount = 'active_offers_count';
  static const String canEditFull = 'can_edit_full';
  static const String canEditLimited = 'can_edit_limited';
  static const String canDisable = 'can_disable';
  static const String canReactivate = 'can_reactivate';
  static const String canDelete = 'can_delete';
  static const String canRenew = 'can_renew';
  static const String canClaim = 'can_claim';
}
